"""Length-aware reward shaping for correct DenoiseRL v2 rollouts.

The shaping term is deliberately multiplicative: incorrect rollouts keep their
original reward, while correct rollouts are scaled linearly from ``1.0`` at zero
generated tokens to ``min_factor`` at ``max_response_length``.
"""

import math
from typing import Tuple

import torch


def linear_length_factor(
    response_lengths: torch.Tensor,
    *,
    max_response_length: int,
    min_factor: float = 0.5,
) -> torch.Tensor:
    """Return factors in ``[min_factor, 1.0]`` for generated response lengths."""
    if max_response_length <= 0:
        raise ValueError(
            f"max_response_length must be > 0, got {max_response_length}."
        )
    if not math.isfinite(min_factor) or not 0.0 <= min_factor <= 1.0:
        raise ValueError(f"min_factor must be finite and in [0, 1], got {min_factor}.")

    lengths = torch.as_tensor(response_lengths)
    if not torch.is_floating_point(lengths):
        lengths = lengths.to(torch.float32)
    if not torch.isfinite(lengths).all():
        raise ValueError("response_lengths must contain only finite values.")
    if torch.any(lengths < 0):
        raise ValueError("response_lengths must be non-negative.")

    normalized_length = lengths.clamp(max=float(max_response_length)) / float(
        max_response_length
    )
    return 1.0 - (1.0 - min_factor) * normalized_length


def apply_correct_length_reward(
    reward_tensor: torch.Tensor,
    *,
    correctness: torch.Tensor,
    response_lengths: torch.Tensor,
    max_response_length: int,
    min_factor: float = 0.5,
) -> Tuple[torch.Tensor, torch.Tensor]:
    """Scale correct rollout rewards by their linear length factor.

    Args:
        reward_tensor: Token-level rewards with batch as the first dimension.
        correctness: One correctness value per rollout; values greater than zero
            are treated as correct.
        response_lengths: Number of tokens actually generated by the policy for
            each rollout. Injected noisy-prefix tokens must not be included.
        max_response_length: Generation budget defining the lower endpoint.
        min_factor: Factor at ``max_response_length``. The factor at length zero
            is always ``1.0``.

    Returns:
        ``(shaped_reward_tensor, effective_factors)``. Effective factors are
        ``1.0`` for incorrect rollouts because their rewards are left unchanged.
    """
    if reward_tensor.ndim < 1:
        raise ValueError("reward_tensor must have a batch dimension.")

    batch_size = reward_tensor.shape[0]
    correctness_t = torch.as_tensor(correctness, device=reward_tensor.device).reshape(-1)
    response_lengths_t = torch.as_tensor(
        response_lengths, device=reward_tensor.device
    ).reshape(-1)
    if correctness_t.numel() != batch_size:
        raise ValueError(
            "correctness must have one value per reward row: "
            f"got {correctness_t.numel()} for batch size {batch_size}."
        )
    if response_lengths_t.numel() != batch_size:
        raise ValueError(
            "response_lengths must have one value per reward row: "
            f"got {response_lengths_t.numel()} for batch size {batch_size}."
        )
    if not torch.isfinite(correctness_t.to(torch.float32)).all():
        raise ValueError("correctness must contain only finite values.")

    factors = linear_length_factor(
        response_lengths_t,
        max_response_length=max_response_length,
        min_factor=min_factor,
    ).to(device=reward_tensor.device, dtype=reward_tensor.dtype)
    correct_mask = correctness_t > 0
    effective_factors = torch.where(
        correct_mask, factors, torch.ones_like(factors)
    )
    broadcast_shape = (batch_size,) + (1,) * (reward_tensor.ndim - 1)
    shaped_reward = reward_tensor * effective_factors.reshape(broadcast_shape)
    return shaped_reward, effective_factors
